create table users (
                       id bigint generated by default as identity ,
                       username varchar(50) unique not null,
                       nickname varchar(100),
                       email varchar(255) unique not null,
                       password_hash varchar(255) not null,
                       role varchar not null,
                       status varchar(50) default 'active',
                       last_login_at timestamp with time zone,

                       created_at timestamp not null,
                       updated_at timestamp,
                       primary key (id)
);


create table profiles (
                          user_id bigint PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
                          is_public boolean default true,
                          avatar_url varchar(500) unique,
                          bio text,
                          location text,
                          gender varchar(20),
                          date_of_birth date,
                          updated_at timestamp
);


create table posts (
                       id bigint generated by default as identity primary key,
                       content text,
                       media JSONB DEFAULT '[]',
                       privacy_level VARCHAR(20) DEFAULT 'public' CHECK (privacy_level IN ('public', 'friends', 'private')),
                       hashtags JSONB DEFAULT '[]',
                       author_id bigint REFERENCES users(id) ON DELETE CASCADE,

                       is_published BOOLEAN DEFAULT TRUE,
                       created_at timestamp,
                       published_at timestamp
);

CREATE TABLE follows (
                         id bigint generated by default as identity,
                         user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                         target_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                         created_at timestamp,

                         primary key (user_id, target_id),
                         CONSTRAINT no_self_follow CHECK (user_id != target_id)
);
CREATE TABLE likes (
                       id bigint generated by default as identity,
                       user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                       target_type VARCHAR(20) NOT NULL CHECK (target_type IN ('post', 'comment', 'story')),
                       target_id UUID NOT NULL,

                       created_at timestamp,

                       primary key (user_id, target_type, target_id)
);

CREATE TABLE refresh_tokens (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id BIGINT NOT NULL,
                                token VARCHAR(2048) NOT NULL,
                                expires_at TIMESTAMP NOT NULL,

                                CONSTRAINT fk_refresh_token_user
                                    FOREIGN KEY (user_id) REFERENCES users(id)
                                        ON DELETE CASCADE
);

-- Создание индексов
CREATE INDEX idx_refresh_user ON refresh_tokens(user_id);
CREATE UNIQUE INDEX idx_refresh_token ON refresh_tokens(token);
